### ISSUE TITLE
jquery hangs on iphone

### ISSUE THREAD

**Issue by m1rose28** [m1rose28/Ridezu#1]
Jquery hangs on the ihpone when switching pages.  If you go to ridezu.com and then click on maps.  It will just hang.  However if you go directly to the page, the page works fine.  

The javascript debugger in safari says that variables aren't initialized, so I think it has to do with the page getting initialized.  It's very touchy.  Even with simple scripts it breaks.

**Comment by txie** [comment]
hmm... never used jquery mobile by myself. But i saw smooth page flows in some hackathon.

**Comment by m1rose28** [comment]
I think I've found a solution but need to code and test.  

http://stackoverflow.com/questions/9221259/jquery-mobile-not-loading-google-map-except-on-refresh

I am thinking of making it one single app, pulling in content via ajax.  that way too the user never sees page transitions and url's.  

as long as the app does not get too big, I think this might be the smarter approach.
